### ISSUE TITLE
[CP] new magic items

### ISSUE THREAD

**Issue by V-Rabbit** [Ouroboros-dnd/Codex#17]
[_Finished Items.pdf](https://github.com/Ouroboros-dnd/Codex/files/7999449/_Finished.Items.pdf)

Contains Chaos Artifact set, Crown of Klothys, and Vines of Pharika

**Comment by V-Rabbit** [comment]
[_WIP Items.pdf](https://github.com/Ouroboros-dnd/Codex/files/8000122/_WIP.Items.pdf)
Contains clarification updates to the Chaos Set, and functional changes to the Vines of Pharika

**Comment by kgirtxd** [comment]
Please review recommended changes sent in discord.

**Comment by V-Rabbit** [comment]
[Relics of Chaos.pdf](https://github.com/Ouroboros-dnd/Codex/files/8010992/Relics.of.Chaos.pdf)
- Finalized removal of proficiency bonuses and attunement requirement of Key of Chaos
- Added description of chaos artifact peices
- Added random properties to Key and Ring of Chaos. 
- Added recommended formatting cards for individual items to reflect Aurora formating for Eye and Hand of Vecna

Changes still pending:
- vines of Pharika

**Comment by V-Rabbit** [comment]
[Pharika's Mortar and Pestle.pdf](https://github.com/Ouroboros-dnd/Codex/files/8011766/Pharika.s.Mortar.and.Pestle.pdf)
- added Pharika's Mortar and Pestle
- renamed vines and merged with Pharika's Mortar and Pestle
- added combined effects for vines and mortar and pestle
- added attunement requirements 
- added instructions for artifact destruction

**Comment by V-Rabbit** [comment]
[Compass of Knowledge.pdf](https://github.com/Ouroboros-dnd/Codex/files/8011770/Compass.of.Knowledge.pdf)
- added compass of knowledge
- changed magic item status from an artifact to very rare magic item

**Comment by V-Rabbit** [comment]
- Typo fixes
- Changed ability cost of _compact kit_
- Removed recharge conflict in _perfect poison_

**Comment by V-Rabbit** [comment]
[Pharika's Mortar and Pestle.pdf](https://github.com/Ouroboros-dnd/Codex/files/8011836/Pharika.s.Mortar.and.Pestle.pdf)
- typo fixes
- changed cost of _compact kit_, is now dependant on wisdom modifier
- removed recharge conflict in _perfect potions_
